@startuml

title DriveHub - diagrama de class

abstract class GestionVehiculo{
    -Vehiculo
    -NumerMatricula
    -Estado
    -TarifaAdicional



    +abstract CalcularTarifaAdicional()
    +abstract TarifaTotal()
    
}

class Compacto extends GestionVehiculo{

    
} 

class SUV extends GestionVehiculo{
    
} 

class Sedan extends GestionVehiculo{
    
} 

class cliente {
    -IdCliente
    -Nombre
}


class GestionKilometraje{
    -Kilometros_en_el_Dia
    -KilometrosTotales
}

class Mantenimiento{
    -Costo
    -Fecha
    -Descripcion
    -Duracion
}

class GestionReserva{
    -FechaInicio
    -FechaFin
    -Vehiculo
    -EstaDisponible

    +DuracionDelAlquiler()
    
}

GestionReserva*--Mantenimiento
GestionReserva*--cliente
GestionVehiculo*--GestionKilometraje
GestionVehiculo-->GestionReserva
 
 @enduml